### PR TITLE
Update the word and pronounce reference

### PR DESCRIPTION
**Pull request by NeroHin**
Fix phonetic alphabet:
- Ubuntu ([ref](https://en.wiktionary.org/wiki/ubuntu))
- Vue([ref](https://vuejs.org/guide/introduction.html#what-is-vue))
- Sudo([ref](https://en.wiktionary.org/wiki/sudo))

Change reference:
- Django([ref](https://www.djangoproject.com/start/overview/))

New word:
- Kubernetes([ref](https://www.youtube.com/watch?v=kTzuEB82hFs&t=16s))
The most popular open-source container cluster management tool.

- Elasticsearch([ref](https://www.youtube.com/watch?v=z71Tl2ikwik))
Part of the ELK solution by Elastic, it's an open-source search engine.

- Grafana([ref](https://ssl.gstatic.com/dictionary/static/pronunciation/2022-03-02/audio/gr/grafana_en_us_1.mp3))
Open-source analytics & monitoring solutions for every database.

- Prometheus([ref](https://ssl.gstatic.com/dictionary/static/pronunciation/2022-03-02/audio/pr/prometheus_en_us_1.mp3))
An open-source monitoring system with a dimensional data model, flexible query language, efficient time series database, and modern alerting approach.

- Redux([ref](https://ssl.gstatic.com/dictionary/static/pronunciation/2022-03-02/audio/re/redux_en_us_1.mp3))
A Predictable State Container for JS Apps, frequently used with React.js.

- verbose([ref](https://www.ldoceonline.com/media/english/breProns/verbose0205.mp3?version=1.2.57))
A word frequently used in machine learning and deep learning tool.

Others:
When I click the audio icon, it will open the pronunciation website in the same window. So I add a method guide that explains how to open the website on a new tab.

### CODE REVIEW

**Comment by NeroHin** [comment]
@pjchender 
Hi Aaron, would you accept contributing to this project now?  
Thank you for your time.

**Review by pjchender — APPROVED** [review]
lgtm

**Comment by pjchender** [comment]
@NeroHin Thanks for your contribution.

**Comment by NeroHin** [comment]
@pjchender Thank your Aaron!

**Pull request merged**
